### ISSUE TITLE
Physical Layer specification ver 3.0 

### ISSUE THREAD

**Issue by ospis12** [enjoy-digital/litesdcard#17]
Hi,
recently I found using google.com with key words: "sd physical specification" this page: 
http://read.pudn.com/downloads188/ebook/881633/SD%203.0/Part_1_Physical_Layer_Specification_Ver3.00_Final_090416.pdf
It contains loads of information about SD protocol, and timings in SD mode. 
Unfortunately this file is marked as "Confidential", 
so most likely you don't want to have anything in common with it.
Just posting it here, since you are working hard on this project.
Good luck cracking this proprietary communication protocol.

**Comment by enjoy-digital** [comment]
Thanks for sharing, since this is confidential (which is really disappointing...) i'm not sure we should keep this open, we have mostly been using the simplified specifications which are already providing most for the information needed.
