### ISSUE TITLE
LiteSDCard for SDcard emulation

### ISSUE THREAD

**Issue by Blobfishman** [enjoy-digital/litesdcard#18]
Hi,
I want to implement a SD-Card to USB (flash drive) adapter by emulating a slave SD-Card and performing all filesystem(fat32) actions on the connected USB flash drive. During my research I found [a similar project on hackday.io](https://hackaday.io/project/19783-sd-card-emulation) referencing this project as a solution for the emulation. After reading the Readme, however, I'm not sure that LiteSDCard is capable of emulating a SD-Card (due to the section Performances) by acting as a slave SD device. 
So my question is: Is the LiteSDCard a SD host and/or a slave SD device (sd card emulatio) implementation?

**Comment by enjoy-digital** [comment]
Hello @Blobfishman,

sorry for the late answer, but LiteSDCard only implements SD Host: it's used to read and write from/to a SD Card from a SoC.
