### ISSUE TITLE
Possible improvement on Altera/Intel

### ISSUE THREAD

**Issue by Martoni** [enjoy-digital/litesdcard#27]
In features README section it's noted that Altera is validated :

```
    Generic PHY validated on Xilinx, Altera, Lattice FPGAs
```

But in Possible improvement it noted : 

```
add support for Altera FPGAs.
```

Is Altera/Intel FPGA supported by liteSDCard ?

Thank

**Comment by enjoy-digital** [comment]
Thanks @Martoni, there was previously only a Xilinx specific PHY that has been replace with vendor agnostic PHY, so all FPGAs are now supported. The README has been updated with https://github.com/enjoy-digital/litesdcard/commit/f460a74f53a4db401e487f70a03a925ab563ce67.
